name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

env:
  ACR_LOGIN_SERVER: actionstestdeploy.azurecr.io
  BASE_ACR_LOGIN_SERVER: actionstestdeploybase.azurecr.io
  BASE_IMAGE_NAME: actionstestdeploybase
  APP_IMAGE_NAME: actionstestdeploy
  CONTAINER_APP_NAME: demotestdeploy
  RESOURCE_GROUP: demo
  IMAGE_TAG: build-${{ github.run_number }}      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check if requirements.txt changed
        id: check_requirements
        run: |
          git fetch origin main --depth=2
          git diff --name-only HEAD^ HEAD | grep -q '^requirements.txt$' && echo "changed=true" >> $GITHUB_OUTPUT || echo "changed=false" >> $GITHUB_OUTPUT

      - name: Log in to BASE ACR
        run: |
          az acr login --name ${{ env.BASE_ACR_LOGIN_SERVER }}

      - name: Build and push base image if requirements.txt changed
        if: steps.check_requirements.outputs.changed == 'true'
        run: |
          docker build -f Dockerfile.base -t ${{ env.BASE_ACR_LOGIN_SERVER }}/${{ BASE_IMAGE_NAME }}:latest .
          docker push ${{ env.BASE_ACR_LOGIN_SERVER }}/${{ BASE_IMAGE_NAME }}:latest

      - name: Log in to ACR
        run: |
          az acr login --name ${{ env.ACR_LOGIN_SERVER }}   

      - name: Build and push actual app image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.APP_IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.APP_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_LOGIN_SERVER/$APP_IMAGE_NAME:${{ env.IMAGE_TAG }}


