name:deploy in CA

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: potluriujwala/app
      IMAGE_TAG: build-${{ github.run_number }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t potluriujwala/app:${{ github.run_number }}

      - name: Push Docker Image to Docker Hub
        run: docker push potluriujwala/app:${{ github.run_number }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name test \
            --resource-group practice \
            --image potluriujwala/app:${{ github.run_number }}
/app:v2
